feat(publisher): permite o uso de ttl por mensagens e filas com ttl zerado
eduzz/rabbit pull request #19
Opened 2023-03-21 20:10 UTC by silvaangelo

feat(publisher): permite o uso de ttl por mensagens e filas com ttl zerado

2023-03-21 20:12 UTC, pokearaujo submitted a review, later dismissed

2023-03-21 20:34 UTC, wesleyserafimeduzz approved these changes, later dismissed

2023-03-21 20:44 UTC, henriquegomes6 requested changes

2023-03-21 20:44 UTC, henriquegomes6 commented on src/DelayQueue.ts
> +    if (!this.options.noTimeout && this.options?.timeout !== undefined && this.options.timeout <= 0) {
deixa esse IF mais legivel

2023-03-22 16:49 UTC, caferrari approved these changes

2023-03-22 20:03 UTC, gustavomfranzin approved these changes

2023-03-22 20:07 UTC, pokearaujo approved these changes

2023-03-22 20:09 UTC, merged